[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mosaic"
version = "1.0.4"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
description = "A simple-ish photographic mosaic generation library."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click",
    "hnswlib",
    "matplotlib",
    "numpy",
    "pillow",
    "requests",
    "scipy",
    "tqdm",
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
    "mypy-extensions",
    "types-requests",
    "types-tqdm",
]

[project.scripts]
mosaic = "mosaic.cli:main"
