name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup 'uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.16"
          enable-cache: true

      - name: Setup Python
        uses: actions/python@v5
        with:
          python-version-file: ".python-version"

      - name: Sync dependencies
        run: uv sync --only-dev

      - name: Run linter
        run: |
          uv run flake8 src
          uv run mypy src

      - name: Run basic test (list all library labels)
        run: |
          uv run mosaic labels
